spring.application.name=trkcel
spring.datasource.hikari.schema=turkcell
spring.datasource.url=http://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=b190758x
server.port=8080